---
# roles/launch/tasks/main.yml

- name: criar gurpos de seguranca
  ec2_group:
    name: "{{ app_name }}"
    description: "{{ app_name }} security group"
    region: "{{ region }}"
    rules: "{{ sec_group_rules }}"
    vpc_id: "{{ vpc_id }}"
  tags: security_groups
  register: app_security_group



- name:  criando servidor
  ec2:
    region: "{{ region }}"
    keypair: "{{ keypair }}"
    zone: "{{ zone }}"
    group: "{{ app_security_group.group_name }}"
    image: "{{ ami }}"
    instance_type: "{{ instance_type }}"
    instance_tags:
      Name: "{{ service_name }}"
    volumes: "{{ volumes }}"
    wait: yes
  register: ec2

- name: adcionando instancias aos grupos de seguranca
  add_host:
    groups: "{{ app_security_group.group_name }}"
    groupname: ec2hosts
    name: "{{ item.public_dns_name }}"
    ansible_host: "{{ item.public_dns_name }}"
    hostname: ec2hosts
  loop: "{{ ec2.instances }}"


- name: Wait for instance to boot
  wait_for:
    host: "{{ item.public_ip }}"
    port: 22
    delay: 30
    timeout: 300
    state: started
  loop: "{{ ec2.instances }}"

