---
# roles/launch/tasks/main.yml

- name: Encontrar ultima versao do ubuntu 
  ec2_ami_find:
    region: "{{ region }}"
    name: "ubuntu/images/hvm-ssd/ubuntu-trusty-14.04-amd64-server-*"
    owner: 099720109477
    sort: name
    sort_order: descending
    sort_end: 1
    no_result_action: fail
  register: ami_result

- name: criar gurpos de seguranca
  ec2_group:
    name: "{{ app_name }}"
    description: "{{ app_name }} security group"
    region: "{{ region }}"
    rules: "{{ sec_group_rules }}"
    vpc_id: "{{ vpc_id }}"
  tags: security_groups
  register: app_security_group



- name:  criando servidor
  ec2:
    region: "{{ region }}"
    keypair: "{{ keypair }}"
    zone: "{{ zone }}"
    group: "{{ app_security_group.group_name }}"
    image: "{{ ami_result.results[0].ami_id }}"
    instance_type: "{{ instance_type }}"
    instance_tags:
      Name: "webapp-{{ service_name }}"
    volumes: "{{ volumes }}"
    wait: yes
  register: ec2

- name: adcionando instancias aos grupos de seguranca
  add_host:
    groups: "{{ app_security_group.group_name }}"
    name: "{{ item.public_dns_name }}"
  loop: "{{ ec2.instances }}"

- name: Wait for instance to boot
  wait_for:
    host: "{{ item.public_ip }}"
    port: 22
    delay: 30
    timeout: 300
    state: started
  loop: "{{ ec2.instances }}"


#- name: Configure instance(s)
#  hosts: 
#  gather_facts: True
#  ...
#  tasks:
#   - name: install  git
#     apt: name=git state=present