---
# tasks file for myapp_infra

- name: para instancias
  ec2:
    instance_ids: "{{ ec2.instances[0].id }}"
    region: '{{ region }}'
    state: stopped
    wait: true
    vpc_subnet_id: "{{ subnets }}"
    assign_public_ip: yes

- ec2_ami_facts:
    filters:
      "tag:Name": "{{app_name}}"
    region: "{{ region }}"
  register: old_ami_result

- name: destroi as imagens antigas 
  ec2_ami:
    region: "{{ region }}"
    image_id: "{{ item.ami_id }}"
    delete_snapshot: yes
    state: absent
  loop: "{{ old_ami_result.results }}"
  ignore_errors: yes

- name: cria imagem
  ec2_ami:
    instance_id: "{{ ec2.instances[0].id }}"
    wait: true
    name: "{{ app_name }}-{{ ec2.instances[0].id }}"
    region: "{{ region }}"
    tags:
      Name: "{{ app_name }}"
      Service: TestService
  register: image


- name: mata instancias
  ec2:
    state: 'absent'
    instance_ids: '{{ ec2.instances[0].id }}'
    region: "{{ region }}"
    

- name: inicia balancer
  ec2_elb_lb:
    name: "{{ app_name }}"
    region: "{{ region }}"
    state: present
    subnets: "{{ subnets }}"
    security_group_ids: "{{ app_security_group.group_id }}"
    connection_draining_timeout: 60
    listeners:
      - protocol: http
        load_balancer_port: 80
        instance_port: 80
    health_check:
        ping_protocol: http # options are http, https, ssl, tcp
        ping_port: 80
        ping_path: "/" # not required for tcp or ssl
        response_timeout: 5 # seconds
        interval: 30 # seconds
        unhealthy_threshold: 5
        healthy_threshold: 5
  tags: load_balancer

- name: configuracao de maquinas para o autoscale
  ec2_lc:
    name: "{{ app_name }}"
    image_id: "{{ image.image_id }}"
    key_name: "{{ keypair }}"
    region: "{{ region }}"
    security_groups: "{{ app_security_group.group_id }}"
    instance_type: "{{ instance_size }}"
  tags: launch_config

- name: create autoscale groups
  ec2_asg:
    name: "{{ app_name }}"
    load_balancers: "{{ app_name }}"
    launch_config_name: "{{ app_name }}"
    min_size: "{{ min_size }}"
    max_size: "{{ max_size }}"
    desired_capacity: "{{ desired_capacity | default(1) }}"
    region: "{{ region }}"
    vpc_zone_identifier: "{{ subnets | join(',') }}"
    health_check_type: EC2
    health_check_period: 300


- name: create scale down  policy
  ec2_scaling_policy:
    state: present
    region: "{{ region }}"
    name: scale-down-policy
    adjustment_type: ChangeInCapacity
    asg_name: "{{ app_name }}"
    scaling_adjustment: -1
    min_adjustment_step: -1
    cooldown: 300
  register: scale_down_policy
  tags: scaling_policy

- name: create scale up policy
  ec2_scaling_policy:
    state: present
    region: "{{ region }}"
    name: scale-up-policy
    adjustment_type: ChangeInCapacity
    asg_name: "{{ app_name }}"
    scaling_adjustment: 1
    min_adjustment_step: 1
    cooldown: 300
  register: scale_up_policy
  tags: scaling_policy

- name: create scale down alarm
  ec2_metric_alarm:
    state: present
    region: "{{ region }}"
    name: "cpu-low"
    metric: CPUUtilization
    namespace: "AWS/EC2"
    statistic: Average
    comparison: "<="
    threshold: 5.0
    period: 300
    evaluation_periods: 3
    unit: "Percent"
    description: "This will alarm when cpu usage average is lower than 5% for 15 minutes "
    dimensions: 
      AutoScalingGroupName: "{{ app_name }}"
    alarm_actions: 
    - "{{ scale_down_policy.arn }}"
  tags: alarm

- name: create scale up alarm
  ec2_metric_alarm:
    state: present
    region: "{{ region }}"
    name: "cpu-high"
    metric: CPUUtilization
    namespace: "AWS/EC2"
    statistic: Average
    comparison: "<="
    threshold: 90.0
    period: 300
    evaluation_periods: 3
    unit: "Percent"
    description: "This will alarm when cpu usage average is higher than 90% for 15 minutes "
    dimensions: 
      AutoScalingGroupName: "{{ app_name }}"
    alarm_actions: 
      - "{{ scale_up_policy.arn }}"
  tags: alarm

