---

- name: configura ec2
  become: true
  apt:
      name: "{{ item }}"
      state: latest
      update_cache: yes
  loop: "{{ packs }}"

- name: install wp
  become: true
  git:
    repo: https://github.com/WordPress/WordPress.git
    dest: "{{ php_site_root }}"

- name: configura nginx
  become: true
  template: "src=nginx.conf dest=/etc/nginx/sites-enabled/{{ php_base_name }}.conf"
  notify: nginx restart

- name: configura wp
  become: true
  template:
    src: wp_config.php
    dest: "{{ php_site_root }}/wp_config.php"
  notify:
    - fpm restart
- name: Generate PHP-FPM pool configuration
  become: true
  template:
    src: fpm-pool.conf
    dest: "{{ php_fpm_pool_conf_path }}/{{ php_pool_name }}.conf"
  notify:
    - fpm restart